---
- name: Install MariaDB, Nginx, and PHP-FPM
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - redis
    - phpmyadmin
    - wp-cli
    - planet4
    - webdev-tools
