---
- name: Clone Planet4 from Github
  git: repo=https://github.com/greenpeace/planet4-base.git dest={{ p4_install_path }}

- name: Add group "planet4"
  group: name=planet4

- name: Add user "planet4"
  user: name=planet4 group=planet4 home={{ p4_install_path }}/

- name: Create planet4 database
  mysql_db: name={{ p4_db_name }} state=present

- name: Create planet4 database user
  mysql_user: name={{ p4_db_user }} password={{ p4_db_password }} priv={{ p4_db_name }}.*:ALL host='localhost' state=present

- name: Copy planet4 config file
  template: src=wp-cli.yml dest={{ p4_install_path }}/wp-cli.yml
  notify:
  - fix webroot permissions

- name: fix webroot permissions
  file:
    path: /var/www
    mode: 0755
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Composer merge requirement configs
  command: chdir=/var/www/planet4-base sudo -u www-data composer config extra.merge-plugin.require "app/{{ composer_nro }}/{{composer_environment}}/composer.json"

- name: Composer install dependencies
  command: chdir=/var/www/planet4-base sudo -u www-data composer install

- name: Composer install Planet4 into the public dir
  command: chdir=/var/www/planet4-base sudo -u www-data composer run-script site-install

- name: Set permissions for the wp-content dirs
  file:
    path: /var/www/planet4-base/public/wp-content/uploads
    mode: 0777
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Remove the gpnl child theme
  file:
    state: absent
    path: /var/www/planet4-base/public/wp-content/themes/planet4-child-theme-netherlands

- name: Clone the planet4-child-theme-netherlands from Github
  git: repo=https://github.com/greenpeace/planet4-child-theme-netherlands.git dest=/var/www/planet4-base/public/wp-content/themes/planet4-child-theme-netherlands

- name: Remove the gpnl-plugin-blocks
  file:
    state: absent
    path: /var/www/planet4-base/public/wp-content/plugins/planet4-gpnl-plugin-blocks

- name: Clone the gpnl-plugin-blocks from Github
  git: repo=https://github.com/greenpeace/planet4-gpnl-plugin-blocks.git dest=/var/www/planet4-base/public/wp-content/plugins/planet4-gpnl-plugin-blocks

- name: fix webroot permissions
  file:
    path: /var/www
    mode: 0755
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy planet4 server block (HTTP)
  template: src=nginx.conf dest=/etc/nginx/sites-available/{{ p4_domain }}.conf

- name: Copy planet4 server block (HTTPS)
  template: src=nginx-ssl.conf dest=/etc/nginx/sites-available/{{ p4_domain }}-ssl.conf

- name: setup nginx symlinks
  file: path=/etc/nginx/sites-enabled/{{ p4_domain }}.conf
        src=/etc/nginx/sites-available/{{ p4_domain }}.conf
        state=link
        force=yes
  notify: restart nginx

- name: setup nginx https symlinks
  file: path=/etc/nginx/sites-enabled/{{ p4_domain }}-ssl.conf
        src=/etc/nginx/sites-available/{{ p4_domain }}-ssl.conf
        state=link
        force=yes
  notify: restart nginx

- name: Start php-fpm Service
  service: name=php7.0-fpm state=started enabled=yes
