path: public

core config:
  dbuser: {{p4_db_user}}
  dbpass: {{p4_db_password}}
  dbname: {{p4_db_name}}
  dbhost: 127.0.0.1
  extra-php: |
        if ( (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $_SERVER['HTTPS']='on';
        }

core install:
  title: Sample Planet 4 website
  url: https://{{p4_domain}}:4430
  admin_user: {{p4_username}}
  admin_email: {{p4_email}}

theme activate:
  - {{p4_active_theme}}
